account/urls.py
from django.conf.urls import url,include
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

urlpatterns = [
	url(r'^login',views.LoginView.as_view(),name='login'),
	url(r'^logout',views.LogoutIndex.as_view(),name='logout'),
	url(r'^profile',views.View_Profile,name='view_profile'),
    url(r'^signup',views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^password_reset_index/',views.PasswordResetIndex.as_view(),name='password_reset_view'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_ \ -]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.PasswordConfirmResetIndex.as_view(),name='password_reset_confirm'),
    url(r'^password_reset_complete_view/',views.PasswordCompleteResetIndex.as_view(),name='password_reset_complete_view'),
    url(r'^password_reset_done_view/',views.PasswordResetDoneIndex.as_view(),name='password_reset_done_view'),
    url(r'^upload',views.UploadIndex.as_view(),name='upload'),
    url(r'^password_change/',views.PasswordChange.as_view(),name='password_change'),
]

blog/urls.py
from django.conf.urls import url 
from . import views

urlpatterns = [
	url(r'^detail/(?P<slug>[\w-]+)$',views.detail.as_view(),name='detail'),
	url(r'^kategori/(?P<kategori>[\w]+)/(?P<page>\d+)$',views.ArtikelKategoriListView.as_view(),name='kategori'),
	url(r'^(?P<page>\d+)$',views.ArtikelListView.as_view(),name='list'),
	url(r'^manage/$',views.ArtikelManageView.as_view(),name='manage'),
	url(r'^manage/update/(?P<pk>\d+)$',views.ArtikelUpdateView.as_view(),name='update'),
	url(r'^manage/delete/(?P<pk>\d+)$',views.ArtikelDeleteView.as_view(),name='delete'),
 	url(r'^create',views.CreateView.as_view(),name='create'),

]

my_site/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.conf.urls.static import static
from django.conf import settings
from ckeditor_uploader import views as uploader_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^artikel/',include('blog.urls',namespace='blog')),
    url(r'^ckeditor/',include('ckeditor_uploader.urls')),
    url(r'^$',views.index.as_view(),name='index'),
    url(r'^account/',include('account.urls',namespace='account')),
    url(r'^promoted',views.PromotedIndex,name='promoted'),
 
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.
from django import forms

class UserProfile(models.Model):
	user = models.OneToOneField(User)
	description = models.CharField(max_length=100,default='',null=True,blank=True)
	city = models.CharField(max_length=100,default='',null=True,blank=True)
	website = models.URLField(default='',null=True,blank=True)
	phone = models.IntegerField(default=62,null=True,blank=True)
	image = models.ImageField(upload_to='profile_image',blank=True,null=True)

	
	def __str__(self):
		return "{}".format(self.user.username)	

	@property
	def get_photo_url(self):
	    if self.image and hasattr(self.image, 'url'):
	        return self.image.url
	    else:
	        return "/static/readit/images/home_bg_alone.jpg"

            

def create_profile(sender,**kwargs):
	if kwargs['created']:
		user_profile = UserProfile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile,sender=User)

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile
from django import forms

class SignupForm(UserCreationForm):

    email = forms.EmailField(max_length=200, help_text='Required')       
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')





class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()


    class Meta:
        model = User
        fields = ['username', 'email']

class UserEdit(forms.ModelForm):
    class Meta:

        model = UserProfile
        fields = ['city','website','description','phone']


    #jenis_kelamin = forms.ChoiceField(widget=forms.RadioSelect,choices=GENDER)
    #tanggal_lahir = forms.DateField(widget=forms.SelectDateWidget(years=TAHUN))    


class UploadForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image']

account/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.views.generic.edit import FormMixin
from django.contrib.auth.models import User 
from django.views.generic import TemplateView
from django.views.generic import TemplateView,DetailView,CreateView,ListView
## confirmation email ##
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import SignupForm,UploadForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.contrib.auth.views import (
    LoginView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView

    )
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.contrib.auth.mixins import LoginRequiredMixin
from .models import UserProfile
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from .forms import UserUpdateForm,UserEdit



class PasswordChange(PasswordChangeView):
    template_name = 'account/password_change.html'
    success_url = reverse_lazy('account:login')



class LogoutIndex(LoginRequiredMixin,LogoutView):
	template_name = 'account/logout.html'




class PasswordResetIndex(PasswordResetView):
    template_name = 'account/password_reset.html'
    success_url = reverse_lazy('account:password_reset_done_view')
    email_template_name = 'account/password_reset_email.html' 

class PasswordResetDoneIndex(PasswordResetDoneView):
    template_name = 'account/password_reset_done.html'

class PasswordConfirmResetIndex(PasswordResetConfirmView):
    template_name = 'account/password_reset_confirm.html'
    success_url = reverse_lazy('account:password_reset_complete_view')

class PasswordCompleteResetIndex(PasswordResetCompleteView):
    template_name = 'account/password_reset_complete.html'

class LoginView(LoginView,FormMixin):
	template_name = 'login.html'


 

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Aktifkan Akun OneClick'
            message = render_to_string('acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Silakan konfirmasi akun kamu dengan link yang sudah kami kirim ke Mail ')
    else:
        form = SignupForm()

    return render(request, 'signup.html', {'form': form})




def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return HttpResponse('Selamat akun kamu sudah aktif dan sudah bisa digunakan ')
    else:
        return HttpResponse('Link tidak valid atau sudah pernah dibuka')

@login_required
def View_Profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = UploadForm(request.POST,
                                   request.FILES,
                                   instance=request.user.userprofile)
        e_form = UserEdit(request.POST,instance=request.user.userprofile)
        if u_form.is_valid() and p_form.is_valid() and e_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Perubahan telah tersimpan')
            return redirect('account:view_profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = UploadForm(instance=request.user.userprofile)
        e_form = UserEdit(instance=request.user.userprofile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
        'e_form': e_form,
        'user':request.user
    }


    return render(request, 'view_profile.html', context)


class UploadIndex(CreateView):
    model = UserProfile
    form_class = UploadForm
    success_url = reverse_lazy('account:view_profile')
    template_name = 'account/upload.html'

account/templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Selamat Datang, terima kasih sudah mau mendaftar.Akun anda saat ini belum aktif dan belum bisa digunakana, untuk mengaktifkannya klik link di bawah ini.
http://{{ domain }}{% url 'account:activate' uidb64=uid token=token %}

Salam dari Admin
B.X.Nzo
{% endautoescape %}

account/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V1</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Login_v1/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Login_v1/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}" >
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Login_v1/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'Login_v1/vendor/css-hamburgers/hamburgers.min.css' %}" >
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Login_v1/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Login_v1/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Login_v1/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'Login_v1/images/img-01.png' %}" alt="IMG">
				</div>

				<form class="login100-form validate-form" method="POST">
					{% csrf_token%}
					<span class="login100-form-title">
						Member Login
					</span>
					{{form.as_p}}
					<div class="container-login100-form-btn">
						<button class="login100-form-btn" type="submit">
							Login
						</button>
					</div>

					<div class="text-center p-t-12">
						<span class="txt1">
							Forgot
						</span>
						<a class="txt2" href="{% url 'account:password_reset_view' %}">
							Password?
						</a>
					</div>

					<div class="text-center p-t-136">
						<a class="txt2" href="{% url 'account:signup' %}">
							Create your Account
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	
	

	
<!--===============================================================================================-->	
	<script src="{% static 'Login_v1/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Login_v1/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'Login_v1/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Login_v1/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Login_v1//tilt/tilt.jquery.min.js' %}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src="{% static 'Login_v1/js/main.js' %}"></script>

</body>
</html>

account/templates/signup.html
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Creative Colorlib SignUp Form</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Custom Theme files -->
<link href="{% static 'signup/style.css' %}" rel="stylesheet" type="text/css" media="all" />
<!-- //Custom Theme files -->
<!-- web font -->
<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
<!-- //web font -->
</head>
<body>
  <!-- main -->
  <div class="main-w3layouts wrapper">
    <h1>Creative SignUp Form</h1>
    <div class="main-agileinfo">
      <div class="agileits-top">
        <form action="#" method="post">
          {% csrf_token %}
      {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="display: none">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
      {% endfor %} 
            <div class="clear"> </div>
          </div>
          <input type="submit" value="SIGNUP">
        </form>
        <p>Don't have an Account? <a href="#"> Login Now!</a></p>
      </div>
    </div>
    <!-- copyright -->
    <div class="colorlibcopy-agile">
      <p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
    </div>
    <!-- //copyright -->
    <ul class="colorlib-bubbles">
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
    </ul>
  </div>
  <!-- //main -->
</body>
</html>

account/templates/view_profile.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
<head>
  <title>Profile</title>
  {% include 'style.html' %}
</head>
<body>
  {% include 'navbar.html' %}
    <section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url('images/bg_1.jpg');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1 class="mb-3 bread">Profile</h1>
          
          </div>
        </div>
      </div>
    </section>
<div class="row" style="margin-top: 20px">
  <div class="container">
  <h3>Profile</h3>
  <p>Username:{{user}}</p>
  <p>First name : {{user.first_name}}</p>
  <p>Last name : {{user.last_name}}</p>
  <p>email : {{user.email}}</p>
  <p>Description: {{user.userprofile.description}}</p>
  <p>Kota: {{user.userprofile.city}}</p>
  <p>Phone: {{user.userprofile.phone}}</p>
  <p>Website: {{user.userprofile.website}}</p>
  <img src="{{ user.userprofile.get_photo_url }}" width="240">
      <div class="content-section">
      <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Ubah Foto</legend>
              {{ u_form|crispy }}
              {{ p_form|crispy }}
              {{e_form|crispy}}


          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Update</button>
          </div>
      </form>

  </div>
  </div>
</div>
{% include 'scripts.html' %}
</body>
</html>