blog/urls.py
from django.conf.urls import url 
from . import views

urlpatterns = [
	url(r'^detail/(?P<slug>[\w-]+)$',views.detail.as_view(),name='detail'),
	url(r'^kategori/(?P<kategori>[\w]+)/(?P<page>\d+)$',views.ArtikelKategoriListView.as_view(),name='kategori'),
	url(r'^(?P<page>\d+)$',views.ArtikelListView.as_view(),name='list'),
	url(r'^manage/$',views.ArtikelManageView.as_view(),name='manage'),
	url(r'^manage/update/(?P<pk>\d+)$',views.ArtikelUpdateView.as_view(),name='update'),
	url(r'^manage/delete/(?P<pk>\d+)$',views.ArtikelDeleteView.as_view(),name='delete'),
 	url(r'^create',views.CreateView.as_view(),name='create'),

]

my_site/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.conf.urls.static import static
from django.conf import settings
from ckeditor_uploader import views as uploader_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^artikel/',include('blog.urls',namespace='blog')),
    url(r'^ckeditor/',include('ckeditor_uploader.urls')),
    url(r'^$',views.index.as_view(),name='index'),
    url(r'^account/',include('account.urls',namespace='account')),
    url(r'^promoted',views.PromotedIndex,name='promoted'),
 
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User


class Artikel(models.Model):
	judul 		= models.CharField(max_length=255)
	content 	= RichTextUploadingField()
	LIST_CATEGORY = (
		('Blog','Blog'),
		('Jurnal','Jurnal'),
		('Berita','Berita')
		)
	kategori = models.CharField(max_length=20,choices=LIST_CATEGORY,default = 'Blog')
	published	= models.DateTimeField(auto_now_add=True)
	updated	 	= models.DateTimeField(auto_now=True)
	slug 		= models.SlugField(blank=True,editable=False)
	author	    = models.ForeignKey(User, null=True)

	def save(self):
		self.slug = slugify(self.judul)
		super().save()

	def get_absolute_url(self):
		url_slug = {'slug':self.slug}
		return reverse('blog:detail',kwargs=url_slug)

	def __str__(self):
		return "{}.{}".format(self.id,self.judul)

blog/forms.py
from django.forms import ModelForm
from .models import Artikel
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django import forms

class ArtikelForm(ModelForm):
	content = forms.CharField(widget=CKEditorUploadingWidget())
	class Meta:
		model = Artikel
		fields = [
			'judul',
			'content',
			'kategori'
		]

blog/views.py
from django.shortcuts import render,redirect
from django.views.generic import (
	ListView,
	DetailView,
	CreateView,
	DeleteView,
	UpdateView,
	TemplateView

	)
#from .forms import ArtikelForm
from .models import Artikel 
from .forms import ArtikelForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.contrib.auth.models import User


	### Penulis ###

class CreateView(UserPassesTestMixin,CreateView):
	template_name = 'blog/create.html'
	form_class = ArtikelForm
	raise_exception = True

	
	def test_func(self):
	    return self.request.user.groups.filter(name='Penulis').exists() 
	
	


	#### Editor User ####

class ArtikelManageView(UserPassesTestMixin,ListView):
	model = Artikel 
	template_name = 'blog/artikel_manage.html'
	context_object_name = 'artikel_list'
	raise_exception = True
	permission_denied_message = 'oke'

	def test_func(self):
	    return self.request.user.groups.filter(name='Editor').exists() 

class ArtikelDeleteView(UserPassesTestMixin,DeleteView):
	model = Artikel 
	template_name = 'blog/artikel_delete_confirmation.html'
	success_url = reverse_lazy('blog:manage')
	raise_exception = True

	def test_func(self):
	    return self.request.user.groups.filter(name='Editor').exists() 

class ArtikelUpdateView(UserPassesTestMixin,UpdateView):
	login_url = None
	form_class = ArtikelForm 
	model = Artikel 
	template_name = 'blog/artikel_update.html'
	raise_exception = True

	def test_func(self):
	    return self.request.user.groups.filter(name='Editor').exists() 

class ArtikelKategoriListView(ListView):
	model = Artikel
	template_name = "blog/kategori_list.html"
	context_object_name = 'artikel_list'
	ordering = ['-published']
	paginate_by = 3

	def get_queryset(self):
		self.queryset = self.model.objects.filter(kategori=self.kwargs['kategori'])
		return super().get_queryset()

	def get_context_data(self,*args,**kwargs):
		kategori_list = self.model.objects.values_list('kategori',flat=True).distinct().exclude(kategori=self.kwargs['kategori'])# sehingga nanti yang muncul sisanya
		#distinct berguna agar kategori yang di tamplikan tidak double
		# model adalah artikel uda di buat di atas, flat adalah untuk membuat list dan isi nya true
		self.kwargs.update({'kategori_list':kategori_list})
		kwargs = self.kwargs
		return super().get_context_data(*args,**kwargs)

class ArtikelPerKategori():
	model = Artikel

	def get_latest_artikel_each_kategori(self):
		kategori_list_v = self.model.objects.values_list('kategori',flat=True).distinct()
		queryset = []

		for kategori in kategori_list_v:
			artikel = self.model.objects.filter(kategori=kategori).latest('published')
			queryset.append(artikel)

		return queryset

"""class Recent():
	model = Artikel


	def get_context_data_recent(self):
		kategori_list_v = self.model.objects.all().latest('published')	
		context = {
		'kategori_list_v':kategori_list_v
		}
		return context
"""


class UserProfileView(ListView):
    #template_name = 'howl/user-profile.html'
    context_object_name = 'user_howls'

    def get_queryset(self):
        author = self.request.user
        u = User.objects.get(username=author)

        return Howl.objects.filter(author=u)

class detail(DetailView):
	model = Artikel 
	template_name = 'blog/detail.html'
	context_object_name = 'artikel'


	def get_context_data(self,*args,**kwargs):
		kategori_list = self.model.objects.values_list('kategori',flat=True).distinct()
		self.kwargs.update({'kategori_list':kategori_list})

		artikel_serupa = self.model.objects.filter(kategori=self.object.kategori).exclude(id=self.object.id)
		self.kwargs.update({'artikel_serupa':artikel_serupa})

		kategori_list_v = self.model.objects.values_list('kategori',flat=True).distinct()
		queryset = []

		for kategori in kategori_list_v:
			artikel = self.model.objects.filter(kategori=kategori).latest('published')
			queryset.append(artikel)
		self.kwargs.update({'recent':queryset})

		kwargs = self.kwargs
		return super().get_context_data(*args,**kwargs)


"""
		queryset = []
		
		for kategori in kategori_list_v:
			artikel = self.model.objects.filter(kategori=kategori).latest('published')
			queryset.append(artikel)"""






"""class recent(TemplateView,ArtikelPerKategori):

	def get_context_data(self):
		querysets = self.get_latest_artikel_each_kategori()
		context = {
		'latest_artikel_list':querysets
		}
		return context"""



class ArtikelListView(ListView):
	model = Artikel 
	template_name = 'blog/artikel.html'
	context_object_name = 'artikel_list'# pengganti objects_list,atau di sebuat object name
	ordering 			= ['-published']
	paginate_by			= 6

	def get_context_data(self,*args,**kwargs):
		kategori_list = self.model.objects.values_list('kategori',flat=True).distinct()
		#distinct berguna agar kategori yang di tamplikan tidak double
		# model adalah artikel uda di buat di atas, flat adalah untuk membuat list dan isi nya true
		
		self.kwargs.update({'kategori_list':kategori_list})
		kwargs = self.kwargs

		return super().get_context_data(*args,**kwargs)

blog/templates/blog/artikel.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>OC|ARTIKEL</title>
{% include "style.html" %}
  </head>
  <body>
    
{% include 'navbar.html' %}
    <!-- END nav -->

    <div class="hero-wrap js-fullheight" style="background-image: url({% static 'readit/images/content_bg.jpg' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start" data-scrollax-parent="true">
          <div class="col-md-12 ftco-animate">
            <h2 class="subheading">Hallo!,Selamat Datang di</h2>
            <h1 class="mb-4 mb-md-0">OneClik</h1>
            <div class="row">
              <div class="col-md-7">
                <div class="text">
                  <p>Halaman Artikel berisi berbagai artikel yang ditulis oleh seorang penulis,jika ada penulisan dan perkataan yang salah mohon di maafkan, <br><br>Salam Admin&Tim</p>
                  <div class="mouse">
                    <a href="#" class="mouse-icon">
                      <div class="mouse-wheel"><span class="ion-ios-arrow-round-down"></span></div>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- START CONTENT -->
<section class="ftco-section">
  <div class="container">
  <div class="container" style="margin-top:0px">
  <div class="row">
    {% for artikel in artikel_list %}
    <div class="col-sm-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title" ><a href="{% url 'blog:detail' artikel.slug %}">{{artikel.judul}}</a></h5>
              <h6 class="card-subtitle mb-2 text-dark">{{artikel.kategori}}</h6>
              <h6 class="card-subtitle mb-2 text-muted">{{artikel.published|date}}</h6>
            </div>
          </div>
      </div>

    {% endfor %}

  </div>
  <div class="row" style="margin-top: 10px">
  <div class="col-md-8" style="position: center;">
    {% if is_paginated %}

      <nav aria-label="artikelPage">
        <ul class="pagination">
          
          {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="{% url 'blog:list' page_obj.previous_page_number%}">Previous</a>
            </li>
        {% else %}
          <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
          {% endif %}
          
          {% for page in paginator.page_range %}
            {% if page is page_obj.number %}
            <li class="page-item active" aria-current="page">
              <span class="page-link" href="#">{{page}}<span class="sr-only">(current)</span></span>
            </li>
            {% else %}
            <li class="page-item">
              <a class="page-link" href="{% url 'blog:list' page %}">{{page}}</a>
            </li>
            {% endif %}
          {% endfor %}
          
          {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="{% url 'blog:list' page_obj.next_page_number%}">Next</a>
            </li>
        {% else %}
          <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
            </li>
          {% endif %}

        </ul>
      </nav>

      {% endif %}

  </div>
</section>



    <footer class="ftco-footer ftco-bg-dark ftco-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="logo"><a href="#">One<span>Click</span>.</a></h2>
              <p>Terima kasih sudah berkunjung, jika ada pertanyaan atau saran ,silakan kirim ke Telegram atau Email.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Ada Pertanyaan ?</h2>
              <div class="block-23 mb-3">
                <ul>
                  <li><span class="icon icon-map-marker"></span><span class="text">Sumatera,Indonesia</span></li>
                  <li><a href="#"><span class="icon icon-phone"></span><span class="text">Telegram +628</span></a></li>
                  <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>
    
  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>



{% include "scripts.html" %}

  </body>

</html>

blog/templates/blog/artikel_delete_confirmation.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h1>Delete Artikel Confirmation</h1>
	<p>Apakah benar anda ingin menghapus artikel berikut:</p>
	<h3>{{artikel.judul}}</h3>
	<p>{{artikel.published}}</p>
	<form method='POST'>
		{% csrf_token %}
		<button type="submit" class="btn btn-outline-primary">Ya</button>
		<a class="btn btn-outline-danger" href="{% url 'blog:manage' %}">Tidak</a>
	</form>
</body>
</html>

blog/templates/blog/artikel_manage.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
  {% include 'style.html' %}
</head>
<body>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Judul</th>
      <th scope="col">Kategori</th>
      <th scope="col">Published</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
   	{% for  artikel in artikel_list %} 
	    <tr>
	      <th scope="row">{{forloop.counter}}</th>
	      <td>{{artikel.judul}}</td>
	      <td>{{artikel.kategori}}</td>
	      <td>{{artikel.published}}</td>
	      <td>
	      <a class="btn btn-danger" href="{% url 'blog:update' artikel.id %}">Edit</a>
				<a class="btn btn-warning" href="{% url 'blog:delete' artikel.id %}">Delete</a>
	      </td>
	    </tr>
    {% endfor %}
  </tbody>
</table>
<div>
  <p><a href="{% url 'index' %}" class="btn btn-info">Home</a></p>
</div>
{% include 'scripts.html' %}
</body>
</html>

blog/templates/blog/artikel_update.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<form method="POST">
		{% csrf_token %}

		<div class="form-group">
			<label for="{{form.content.id_for_label}}">
			{{form.media}}
			{{form.as_p}}:
			</label>
		</div>
		<button type="submit" class="btn btn-primary">Tambah</button>
	</form>

</body>
</html>

blog/templates/blog/create.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h3>Tambah Artikel</h3>
	<form method="POST">
		{% csrf_token %}

		<div class="form-group">
			<label for="{{form.content.id_for_label}}">
			{{form.media}}
			{{form.as_p}}:
			</label>
		</div>
		<p>
		<button type="submit" class="btn btn-primary">Tambah</button>
		<a class="btn btn-primary" href="{% url 'index' %}">Batal</a></p>
	</form>
</body>
</html>

blog/templates/blog/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>OnClick</title>

{% include "style.html" %}

  </head>
  <body>
    
{% include 'navbar.html' %}
    <!-- END nav -->

    
    <section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url('images/bg_1.jpg');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1 class="mb-3 bread">OneClick Blog</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'index' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a href="{% url 'blog:list' 1%}">Blog <i class="ion-ios-arrow-forward"></i></a></span> <span>Blog Single <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>

   <section class="ftco-section ftco-degree-bg">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 ftco-animate">
            <h3>{{artikel.judul}}</h3>
            <p>{{artikel.kategori}} | {{artikel.published}}</p>
            <p>{{artikel.content|safe}}</p>
            
            <div class="about-author d-flex p-4 bg-light">
              <div class="bio mr-5">
                <img src="images/person_1.jpg" alt="Image placeholder" class="img-fluid mb-4">
              </div>
              <div class="desc">
                <h3></h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
              </div>
            </div>



          </div> <!-- .col-md-8 -->
          <div class="col-lg-4 sidebar pl-lg-5 ftco-animate">
            <div class="sidebar-box">
              <form action="#" class="search-form">
                <div class="form-group">
                  <span class="icon icon-search"></span>
                  <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                </div>
              </form>
            </div>
            <div class="sidebar-box ftco-animate">
              <div class="categories">
                <h3>Categories</h3>
                {% for kategori in kategori_list %}
                <li><p><a href="{% url 'blog:kategori' kategori 1 %}">{{kategori}}</a></p></li>
                {% endfor %}
              </div>
            </div>
            <div class="sidebar-box ftco-animate">
              <h3>Terbaru</h3>
              <div class="block-21 mb-4 d-flex">
                <div class="text">
                  {% for artikel in recent %}
                    {% if forloop.counter is not 3 %}
                  <h3 class="heading"><a href="{% url 'blog:detail' artikel.slug %}">{{artikel.judul}}</a></h3>
                  <p>{{artikel.published}}</p><br>
                    {% endif %}
                  {% endfor %}

                </div>
              </div>
            </div>

            <div class="sidebar-box ftco-animate">
              <h3>Artikel Serupa</h3>
              <div class="block-21 mb-4 d-flex">
                <div class="text">
                  {% for artikel in artikel_serupa %}
                    {% if forloop.counter is not 2 %}
                  <h3 class="heading"><a href="{% url 'blog:detail' artikel.slug %}">{{artikel.judul}}</a></h3>
                  <p>{{artikel.published}}</p><br>
                    {% endif %}
                  {% endfor %}

                </div>
              </div>
            </div>

          </div>

        </div>
      </div>
    </section> <!-- .section -->

    <footer class="ftco-footer ftco-bg-dark ftco-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="logo"><a href="#">One<span>CLick</span>.</a></h2>
              <p>Terima kasih sudah berkunjung, jika ada pertanyaan atau saran ,silakan kirim ke Telegram atau Email.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Ada Pertanyaan ?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">Sumatera,Indonesia</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">Telegram +628</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>
    
  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


{% include "scripts.html" %}

  </body>
</html>

blog/templates/blog/kategori_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>OC|ARTIKEL</title>

{% include "style.html" %}

  </head>
  <body>
    
{% include 'navbar.html' %}
    <!-- END nav -->

    <div class="hero-wrap js-fullheight" style="background-image: url({% static 'readit/images/content_bg.jpg' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start" data-scrollax-parent="true">
          <div class="col-md-12 ftco-animate">
            <h2 class="subheading">Hallo!,Selamat Datang di</h2>
            <h1 class="mb-4 mb-md-0">OneClik</h1>
            <div class="row">
              <div class="col-md-7">
                <div class="text">
                  <p>Halaman Artikel berisi berbagai artikel yang ditulis oleh seorang penulis,jika ada penulisan dan perkataan yang salah mohon di maafkan, <br><br>Salam Admin&Tim</p>
                  <div class="mouse">
                    <a href="#" class="mouse-icon">
                      <div class="mouse-wheel"><span class="ion-ios-arrow-round-down"></span></div>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- START CONTENT -->
<section class="ftco-section">
  <div class="container">
  <div class="container" style="margin-top:0px">
  <div class="row">
    {% for artikel in artikel_list %}
    <div class="col-sm-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title" ><a href="{% url 'blog:detail' artikel.slug %}">{{artikel.judul}}</a></h5>
              <h6 class="card-subtitle mb-2 text-muted">{{artikel.published|date}}</h6>
            </div>
          </div>
      </div>

    {% endfor %}

  </div>
  <div class="row" style="margin-top: 10px">
  <div class="col-md-8" style="position: center;">
    {% if is_paginated %}

      <nav aria-label="artikelPage">
        <ul class="pagination">
          
          {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="{% url 'blog:kategori' kategori page_obj.previous_page_number%}">Previous</a>
            </li>
        {% else %}
          <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
          {% endif %}
          
          {% for page in paginator.page_range %}
            {% if page is page_obj.number %}
            <li class="page-item active" aria-current="page">
              <span class="page-link" href="#">{{page}}<span class="sr-only">(current)</span></span>
            </li>
            {% else %}
            <li class="page-item">
              <a class="page-link" href="{% url 'blog:kategori' kategori page %}">{{page}}</a>
            </li>
            {% endif %}
          {% endfor %}
          
          {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="{% url 'blog:kategori' kategori page_obj.next_page_number%}">Next</a>
            </li>
        {% else %}
          <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
            </li>
          {% endif %}

        </ul>
      </nav>

      {% endif %}

  </div>

</section>



    <footer class="ftco-footer ftco-bg-dark ftco-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="logo"><a href="#">One<span>Click</span>.</a></h2>
              <p>Terima kasih sudah berkunjung, jika ada pertanyaan atau saran ,silakan kirim ke Telegram atau Email.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Ada Pertanyaan ?</h2>
              <div class="block-23 mb-3">
                <ul>
                  <li><span class="icon icon-map-marker"></span><span class="text">Sumatera,Indonesia</span></li>
                  <li><a href="#"><span class="icon icon-phone"></span><span class="text">Telegram +628</span></a></li>
                  <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>
    
  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>



{% include "scripts.html" %}

  </body>
</html>