account/urls.py
from django.conf.urls import url,include
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

urlpatterns = [
	url(r'^login',views.LoginView.as_view(),name='login'),
	url(r'^logout',views.LogoutIndex.as_view(),name='logout'),
	url(r'^profile',views.View_Profile,name='view_profile'),
    url(r'^signup',views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^password_reset_index/',views.PasswordResetIndex.as_view(),name='password_reset_view'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_ \ -]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.PasswordConfirmResetIndex.as_view(),name='password_reset_confirm'),
    url(r'^password_reset_complete_view/',views.PasswordCompleteResetIndex.as_view(),name='password_reset_complete_view'),
    url(r'^password_reset_done_view/',views.PasswordResetDoneIndex.as_view(),name='password_reset_done_view'),
    url(r'^upload',views.UploadIndex.as_view(),name='upload'),
    url(r'^password_change/',views.PasswordChange.as_view(),name='password_change'),
]

blog/urls.py
from django.conf.urls import url 
from . import views

urlpatterns = [
	url(r'^detail/(?P<slug>[\w-]+)$',views.detail.as_view(),name='detail'),
	url(r'^kategori/(?P<kategori>[\w]+)/(?P<page>\d+)$',views.ArtikelKategoriListView.as_view(),name='kategori'),
	url(r'^(?P<page>\d+)$',views.ArtikelListView.as_view(),name='list'),
	url(r'^manage/$',views.ArtikelManageView.as_view(),name='manage'),
	url(r'^manage/update/(?P<pk>\d+)$',views.ArtikelUpdateView.as_view(),name='update'),
	url(r'^manage/delete/(?P<pk>\d+)$',views.ArtikelDeleteView.as_view(),name='delete'),
 	url(r'^create',views.CreateView.as_view(),name='create'),

]

my_site/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.conf.urls.static import static
from django.conf import settings
from ckeditor_uploader import views as uploader_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^artikel/',include('blog.urls',namespace='blog')),
    url(r'^ckeditor/',include('ckeditor_uploader.urls')),
    url(r'^$',views.index.as_view(),name='index'),
    url(r'^account/',include('account.urls',namespace='account')),
    url(r'^promoted',views.PromotedIndex,name='promoted'),
 
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>OneClick | HOME</title>
    {% include "style.html" %}
  </head>
  <body>
    
{% include "navbar.html" %}
    <!-- END nav -->
    
    <div class="hero-wrap js-fullheight" style="background-image: url({% static 'readit/images/home_bg2.jpg' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start" data-scrollax-parent="true">
          <div class="col-md-12 ftco-animate">
          	<h2 class="subheading">Hallo!,Selamat Datang di</h2>
          	<h1 class="mb-4 mb-md-0">One Click</h1>
          	<div class="row">
          		<div class="col-md-7">
          			<div class="text">
	          			<p>Temukan informasi dari website ini,Jika ada pertanyaan atau saran silakan hubungi admin melalui Telegram atau Email</p>
	          			<div class="mouse">
										<a href="#" class="mouse-icon">
											<div class="mouse-wheel"><span class="ion-ios-arrow-round-down"></span></div>
										</a>
									</div>
								</div>
          		</div>
          	</div>
          </div>
        </div>
      </div>
    </div>
    <section class="ftco-section">
      <div class="container">
      {% for artikel in artikels %}
        <div class="row">
          <div class="col-md-12">

            <div class="case">
              <div class="row">
                <div class="col-md-6 col-lg-6 col-xl-8 d-flex">
                  <a href="{% url 'blog:detail' artikel.slug %}" class="img w-100 mb-3 mb-md-0" style="background-image: url({% static 'readit/images/home_bg1.jpg' %});"></a>
                </div>
                <div class="col-md-6 col-lg-6 col-xl-4 d-flex">
                  <div class="text w-100 pl-md-3">
                    <span class="subheading">Illustration</span>
                    <h2><a href="{% url 'blog:detail' artikel.slug %}">{{artikel.judul}}</a></h2>
                    <ul class="media-social list-unstyled">
                      <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                      <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                      <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                    <div class="meta">
                      <p class="mb-0"><a href="#">{{artikel.published}}</p>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
            </div>
            </div>
        </div>       
      </div>
    </section>




<!-- START FOOTER -->

    <footer class="ftco-footer ftco-bg-dark ftco-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="logo"><a href="#">One<span>Click</span>.</a></h2>
              <p>Terima kasih sudah berkunjung, jika ada pertanyaan atau saran ,silakan kirim ke Telegram atau Email.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Ada Pertanyaan ?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">Sumatera,Indonesia</span></li>
	                <li><a href="https://t.me/bensweb"><span class="icon icon-phone"></span><span class="text">Telegram </span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>
    
  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


{% include "scripts.html" %}
  </body>

</html>

templates/navbar.html
    <nav class="navbar px-md-0 navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="{% url 'index' %}">One<i>Clik</i>.</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
          <ul class="navbar-nav ml-auto">
              <li class="nav-item active"><a href="{% url 'index' %}" class="nav-link">Home</a></li>
              <li class="nav-item"><a href="{% url 'blog:list' 1 %}" class="nav-link">Artikel</a></li>
            {% if user.is_authenticated %}
              <li class="nav-item"><a href="{% url 'account:view_profile' %}" class="nav-link">Profile</a></li>           
              <!-- Position -->
              <div class="btn-group">
                <button type="button" class="btn btn-success"><a href="{% url 'promoted' %}">Postition</a></button>
                <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'blog:create' %}">Penulis</a>
                  <a class="dropdown-item" href="{% url 'blog:manage' %}">Editor</a>
              </div><br>
              <br>
              <!-- account -->
              <div class="btn-group">
                <button type="button" class="btn btn-info">Akun</button>
                <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'account:password_change' %}">Ubah Pass</a>
                  <a class="dropdown-item" href="{% url 'account:password_reset_view' %}">Lupa Pass</a>
                  <a class="dropdown-item" href="{% url 'account:logout' %}">Keluar</a>
              </div>
            {% else %}
              <li class="nav-item"><a href="{% url 'account:login' %}" class="nav-link">Login</a></li>
              <li class="nav-item"><a href="contact.html" class="nav-link">Lupa Password ?</a></li>  
              <li class="nav-item"><a href="{% url 'account:signup' %}" class="nav-link">Daftar</a></li> 
            {% endif %}   
          </ul>
	      </div>
	    </div>
	  </nav>

templates/promoted.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Promoted</title>
	    {% include "style.html" %}


</head>
<body>
{% include "navbar.html" %}

    <div class="hero-wrap js-fullheight" style="background-image: url(#);" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start" data-scrollax-parent="true">
          <div class="col-md-12 ftco-animate">
          	<h2 class="subheading">Hallo!,Selamat Datang di</h2>
          	<h1 class="mb-4 mb-md-0">One Click Position</h1>
          	<div class="row">
          		<div class="col-md-7">
          			<div class="text">
	          			<p>Ingin mendapatkan Jabatan dan gabung di Group, saat ini kita mempunya dua gruop yaitu Penulis dan Editor<br>
	          				  {% for i in a %}
						      Saat ini anda tergabung di gruop : {{i}}
						      {% endfor %}<br>
						      Jika ingin bergabung silakan hubungi admin melalui telegram
						      <li><a href="https://t.me/bensweb"><span class="icon icon-phone"></span><span class="text">Telegram </span></a></li>
						      </p>
	          			<div class="mouse">
										<a href="#" class="mouse-icon">
											<div class="mouse-wheel"><span class="ion-ios-arrow-round-down"></span></div>
										</a>
									</div>
								</div>
          		</div>
          	</div>
          </div>
        </div>
      </div>


{% include "scripts.html" %}
</body>
</html>

templates/scripts.html
 {% load static %}
  <script src="{% static 'readit/js/jquery.min.js' %}"></script>
  <script src="{% static 'readit/js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'readit/js/popper.min.js' %}"></script>
  <script src="{% static 'readit/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'readit/js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'readit/js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'readit/js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'readit/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'readit/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'readit/js/aos.js' %}"></script>
  <script src="{% static 'readit/js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'readit/js/scrollax.min.js' %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static 'readit/js/google-map.js' %}"></script>
  <script src="{% static 'readit/js/main.js' %}"></script>
    

templates/style.html
{% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'readit/css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'readit/css/animate.css' %}">
    
    <link rel="stylesheet" href="{% static 'readit/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'readit/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'readit/css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'readit/css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'readit/css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'readit/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'readit/css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'readit/css/style.css' %}">